config/routes.rb
Rails.application.routes.draw do
  resources :entities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/datasource_credit.rb
class DatasourceCredit < LexiconRecord
end

app/models/entity.rb
class Entity < ApplicationRecord
end

app/models/lexicon_record.rb
class LexiconRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :lexicon
  connects_to database: { reading: :lexicon }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[ show edit update destroy ]

  # GET /entities or /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1 or /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to entity_url(@entity), notice: "Entity was successfully created." }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: "Entity was successfully updated." }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: "Entity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entity_params
      params.require(:entity).permit(:name, :nature, :centroid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Nature:</strong>
    <%= entity.nature %>
  </p>

  <p>
    <strong>Centroid:</strong>
    <%= entity.centroid %>
  </p>

</div>

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :nature, style: "display: block" %>
    <%= form.text_field :nature %>
  </div>

  <div>
    <%= form.label :centroid, style: "display: block" %>
    <%= form.text_field :centroid %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entities</h1>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
    <p>
      <%= link_to "Show this entity", entity %>
    </p>
  <% end %>
</div>

<%= link_to "New entity", new_entity_path %>

app/views/entities/new.html.erb
<h1>New entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <%= link_to "Edit this entity", edit_entity_path(@entity) %> |
  <%= link_to "Back to entities", entities_path %>

  <%= button_to "Destroy this entity", @entity, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agtech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>